version: '3'

services:
    # NGINX + FPM + PHP 8.3
    app:
        image: wendelladriel/laravel-exa
        container_name: laravel-exa
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                - M1_PROCESSOR=${M1_PROCESSOR}
                - XDEBUG_ENABLED=${XDEBUG_ENABLED}
        volumes:
            - ./:/var/www
        ports:
            - "${APP_EXTERNAL_PORT}:80"
            - "${APP_EXTERNAL_PORT_SSL}:443"
        networks:
            - laravel-exa
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        depends_on:
            - redis
            - mysql

    # REDIS
    redis:
        image: wendelladriel/laravel-exa-redis
        container_name: laravel-exa-redis
        build:
            context: .
            dockerfile: docker/redis/Dockerfile
        ports:
            - "${REDIS_EXTERNAL_PORT}:6379"
        volumes:
            - ./docker/redis/data:/data
        networks:
            - laravel-exa
        healthcheck:
            test: ["CMD", "redis-cli", "-h", "${REDIS_HOST:-localhost}", "-p", "${REDIS_PORT}:-6379", "-a", "${REDIS_PASSWORD:-null}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    # MYSQL
    mysql:
        image: mysql:8.0
        container_name: laravel-exa-db
        ports:
            - "${DB_EXTERNAL_PORT}:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - laravel-exa
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USER:-exa} -p${DB_PASSWORD:-secret}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    # MAILPIT
    mailpit:
        image: axllent/mailpit
        container_name: laravel-exa-mailpit
        ports:
            - "${MAILPIT_EXTERNAL_PORT_SMTP}:1025"
            - "${MAILPIT_EXTERNAL_PORT_HTTP}:8025"
        networks:
            - laravel-exa

    # SWAGGER
    swagger:
        image: wendelladriel/laravel-exa-swagger
        container_name: laravel-exa-swagger
        build:
            context: .
            dockerfile: docker/swagger/Dockerfile
        restart: always
        ports:
            - "${SWAGGER_EXTERNAL_PORT}:8080"

networks:
    laravel-exa:
        driver: bridge

volumes:
    dbdata:
        driver: local
